{% set name = "pytest-cov" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 33c97eda2e049a0c5298e91f519302a1334c26ac65c1a483d6206fd458361af1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  # latest version of the coverage 7.11.0 is not available for the py<310
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
    - hatch-fancy-pypi-readme
  run:
    - python
    - coverage >=7.10.6
    - toml
    - pytest >=7
    - pluggy >=1.2

# Tests disabled. Reason - No module named 'process_tests' -> https://pypi.org/project/process-tests (pkg not in  the main channel)
test:
  imports:
    - pytest_cov
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-cov
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest plugin for measuring coverage
  description: |
    This plugin produces coverage reports. Compared to just using coverage run this plugin does some extras:
    * Subprocess support: you can fork or run stuff in a subprocess and will get covered without any fuss.
    * Xdist support: you can use all of pytest-xdist's features and still get coverage.
    * Consistent pytest behavior. If you run coverage run -m pytest you will have slightly different sys.path (CWD will be in it, unlike when running pytest).
    All features offered by the coverage package should work, either through pytest-cov's command line options or through coverage's config file.
  dev_url: https://github.com/pytest-dev/pytest-cov
  doc_url: https://pytest-cov.readthedocs.io

extra:
  recipe-maintainers:
    - dopplershift
    - nicoddemus
