{% set name = "pytest-cov" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-cov-{{ version }}.tar.gz
  sha256: 3904b13dfbfec47f003b8e77fd5b589cd11904a21ddf1ab38a64f204d6a10ef6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
  run:
    - python
    - pytest >=4.6
    - coverage >=5.2.1
    - toml

test:
  imports:
    - pytest_cov
  requires:
    - pip
    - ripgrep
  commands:
    - pip check
    - pytest --traceconfig | rg pytest-cov-{{ version }}

about:
  home: https://github.com/pytest-dev/pytest-cov
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest plugin for measuring coverage
  description: |
    This plugin produces coverage reports. Compared to just using coverage run this plugin does some extras:
    * Subprocess support: you can fork or run stuff in a subprocess and will get covered without any fuss.
    * Xdist support: you can use all of pytest-xdist's features and still get coverage.
    * Consistent pytest behavior. If you run coverage run -m pytest you will have slightly different sys.path (CWD will be in it, unlike when running pytest).
    All features offered by the coverage package should work, either through pytest-cov's command line options or through coverage's config file.
  dev_url: https://github.com/pytest-dev/pytest-cov
  doc_url: https://pytest-cov.readthedocs.io

extra:
  recipe-maintainers:
    - dopplershift
    - nicoddemus
