{% set name = "pytest-cov" %}
{% set version = "6.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-cov/pytest_cov-6.3.0.tar.gz
  sha256: 35c580e7800f87ce892e687461166e1ac2bcb8fb9e13aea79032518d6e503ff2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools >=30.3.0
  run:
    - python
    - pytest >=6.2.5
    - coverage >=7.5
    - toml
    - pluggy >=1.2

test:
  imports:
    - pytest_cov
  requires:
    - pip
    - ripgrep
    - py
  commands:
    - pip check
    - pytest --traceconfig | rg pytest-cov-{{ version }}

about:
  home: https://github.com/pytest-dev/pytest-cov
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest plugin for measuring coverage
  description: |
    This plugin produces coverage reports. Compared to just using coverage run this plugin does some extras:
    * Subprocess support: you can fork or run stuff in a subprocess and will get covered without any fuss.
    * Xdist support: you can use all of pytest-xdist's features and still get coverage.
    * Consistent pytest behavior. If you run coverage run -m pytest you will have slightly different sys.path (CWD will be in it, unlike when running pytest).
    All features offered by the coverage package should work, either through pytest-cov's command line options or through coverage's config file.
  dev_url: https://github.com/pytest-dev/pytest-cov
  doc_url: https://pytest-cov.readthedocs.io

extra:
  recipe-maintainers:
    - dopplershift
    - nicoddemus
