{% set name = "pytest-cov" %}
{% set version = "2.6.1" %}
{% set sha256 = "0ab664b25c6aa9716cbf203b17ddb301932383046082c081b9848a0edf5add33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    noarch: python
    script: python -m pip install --no-deps --ignore-installed .
    number: 0

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools
    - pytest
    - coverage

test:
  commands:
    - "py.test --traceconfig | grep pytest-cov-{{version}}"

about:
  home: https://github.com/pytest-dev/pytest-cov
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pytest plugin for measuring coverage'
  dev_url: https://github.com/pytest-dev/pytest-cov

extra:
  recipe-maintainers:
    - dopplershift
    - nicoddemus
