{% set name = "pytest-cov" %}
{% set version = "2.6.1" %}
{% set sha256 = "0ab664b25c6aa9716cbf203b17ddb301932383046082c081b9848a0edf5add33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    noarch: python
    script: python -m pip install --no-deps --ignore-installed .
    number: 0

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools
    - pytest
    - coverage

test:
  commands:
    - "py.test --traceconfig | grep pytest-cov-{{version}}"                                 # [not win]
    - py.test --traceconfig | findstr pytest-cov-{{version}} && (exit /b 0) || (exit /b 1)  # [win]


about:
  home: https://github.com/pytest-dev/pytest-cov
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pytest plugin for measuring coverage'
  description: |
    pytest-cov produces coverage reports.It supports centralised testing and
    distributed testing in both load and each modes.It also supports coverage
    of subprocesses.
  dev_url: https://github.com/pytest-dev/pytest-cov
  doc_url: https://pytest-cov.readthedocs.io/en/latest/
  doc_source_url: https://github.com/pytest-dev/pytest-cov/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - dopplershift
    - nicoddemus
