travis:
  secure:
    BINSTAR_TOKEN: MerfgbHKBwCMpcnivkCS0OAvJ40VJEkWynaQMK69h4QrL/R0nfmY3dLq08vLvLff6jktgmKbyOYPXQ4eXIwnqcewCOR//8nQ8oBzdZDp+/AExlWRDVnSHblhRi384Xva+e4vwuXGqBm1QiD3iYtFBDMEOjNPaV6J/6ScTo1LtbXioAx1Gg7HwB4fSsM4NWuCJ2vFtz4aZ41DXHLIsDaIWKQFVI5qpYU/hl/zsCq+jOO8qJp1lxLBGyqOBEk01Zr0Ny3HORHxBbYnkYbkiUPsgQKdOFTJAcZAkrMqcrMrUgGhLgA5CBLemWK5X3J2Y1eO8i8kc07XTfvT4MifLt193EqjQXeqOy4V+bmHD1IK01v7D3BtlCa+7uKE/T5YBftwU72oST7+npO8Y+Z/J6kOfT1FZkEYl6/szYCnd1MYQlv9wtLyInQwxhQWkWWo5kRLIsYySE/BO8/UEtQhFebRxDCiILTbY98l5xVCm3AIhR0Z3HmXmNsGoGSrwpowgcdXIhDkTblBYZSKZy5zQyz+VrmrcCvsCaOHQ3FR1EDet28fvFwZhU9JSKj+jGXkBDuZjw49U1TqtH7u8xikLX5K2gyR5nF+jMosDAQCx4g0X7BArXLKen9OlA0jUgg/Ki6ngu+JQ06KUKxhuUTkSKCTawGc9ZFjSoFzRMgCKmxYCbg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
